CREATE TABLE IF NOT EXISTS app_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_name VARCHAR(120) NOT NULL UNIQUE,
    value_text VARCHAR(2000) NOT NULL,
    description VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO app_settings (key_name, value_text, description)
SELECT 'support_email', 'support@talentforge.ai', 'Primary support contact'
WHERE NOT EXISTS (SELECT 1 FROM app_settings WHERE key_name = 'support_email');

INSERT INTO app_settings (key_name, value_text, description)
SELECT 'brand_name', 'TalentForge', 'Brand display name'
WHERE NOT EXISTS (SELECT 1 FROM app_settings WHERE key_name = 'brand_name');

INSERT INTO app_settings (key_name, value_text, description)
SELECT 'require_2fa_admin', 'false', 'Whether admin users must use two-factor auth'
WHERE NOT EXISTS (SELECT 1 FROM app_settings WHERE key_name = 'require_2fa_admin');

INSERT INTO app_settings (key_name, value_text, description)
SELECT 'ip_allowlist', '', 'Allowed admin IP list, newline separated'
WHERE NOT EXISTS (SELECT 1 FROM app_settings WHERE key_name = 'ip_allowlist');

INSERT INTO app_settings (key_name, value_text, description)
SELECT 'promo_consent_required', 'true', 'Whether recruiter consent is required before repost'
WHERE NOT EXISTS (SELECT 1 FROM app_settings WHERE key_name = 'promo_consent_required');
